# Generated by Django 5.0.6 on 2024-05-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_loanrequestform_transaction_receiver_account_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender_account_no',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account_no',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(5, 'Money Transfer'), (1, 'Deposit'), (3, 'Loan'), (2, 'Withdrawal'), (4, 'Loan Paid')], null=True),
        ),
    ]
