# Generated by Django 5.0.6 on 2024-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_receiver_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account_no',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(2, 'Withdrawal'), (5, 'Money Transfer'), (3, 'Loan'), (1, 'Deposit'), (4, 'Loan Paid')], null=True),
        ),
    ]
