# Generated by Django 5.0.6 on 2024-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_sender_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(5, 'Money Transfer'), (2, 'Withdrawal'), (1, 'Deposit'), (4, 'Loan Paid'), (3, 'Loan')], null=True),
        ),
    ]
