# Generated by Django 5.0.6 on 2024-05-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(4, 'Loan Paid'), (2, 'Withdrawal'), (3, 'Loan'), (1, 'Deposit'), (5, 'Money Transfer')], null=True),
        ),
    ]
