# Generated by Django 5.0.6 on 2024-05-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0009_remove_transaction_sender_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account_no',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(4, 'Loan Paid'), (5, 'Money Transfer'), (2, 'Withdrawal'), (1, 'Deposit'), (3, 'Loan')], null=True),
        ),
    ]
